# '*.{ts,tsx,js}':
#   - 'eslint --cache --cache-location ./node_modules/.cache/.eslintcache --fix'
#   - 'prettier --log-level warn --write'
# '*.{json,yml,scss}': 'prettier --log-level warn --write'
